# Setup
title:        Tau Systems theory group
tagline:      created by M. Gracia-Linares
baseurl:      /tausystems.github.io
paginate:     1
locale:       "en"

# About/contact
author:
  name:       M. Gracia-Linares
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
